# Teleop configuration for PS4 Navigation joystick
teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.4
  scale_linear_turbo: 2.0 # TODO: should this be 1.0?
  axis_angular: 0
  scale_angular: 1.4 # TODO: should this be 1.0?
  enable_button: 4
  enable_turbo_button: 5
joy_node:
  deadzone: 0.1 # TODO: should this be 0.02?
  autorepeat_rate: 20
  dev: /dev/input/ps4
