# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Joint1:
    has_velocity_limits: true
    max_velocity: 3.11
    has_acceleration_limits: true
    max_acceleration: 8.8
  Joint2:
    has_velocity_limits: true
    max_velocity: 3.11
    has_acceleration_limits: true
    max_acceleration: 8.8
  Joint3:
    has_velocity_limits: true
    max_velocity: 3.11
    has_acceleration_limits: true
    max_acceleration: 8.8
  Joint4:
    has_velocity_limits: true
    max_velocity: 3.11
    has_acceleration_limits: true
    max_acceleration: 8.8
  Joint5:
    has_velocity_limits: true
    max_velocity: 3.11
    has_acceleration_limits: true
    max_acceleration: 8.8
  Joint6:
    has_velocity_limits: true
    max_velocity: 3.11
    has_acceleration_limits: true
    max_acceleration: 8.8
