moose_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

moose_velocity_controller:
  type: "double_diff_drive_controller/DoubleDiffDriveController"
  drive_motor_joint: 'drive_motor'
  steer_motor_joint: 'steer_motor'
  # left_wheel: ['front_left_wheel', 'front_mid_left_wheel', 'rear_mid_left_wheel', 'rear_left_wheel']
  # right_wheel: ['front_right_wheel', 'front_mid_right_wheel', 'rear_mid_right_wheel', 'rear_right_wheel']
  publish_rate: 20
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Wheel separation and radius multipliers
  wheel_separation: 1.3468  # m
  wheel_radius: 0.3175 # m
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Motor gear ratios
  drive_motor_gear_ratio: 20.43
  steer_motor_gear_ratio: 118.147998746

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 10.0    # m/s
      has_acceleration_limits: true
      max_acceleration       : 100.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 8.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 80.0   # rad/s^2

ekf_localization:
  frequency: 50
  two_d_mode: true
  odom0: /moose_velocity_controller/odom
  odom0_config: [false, false, false,
                 false, false, false,
                 true, true, false,
                 false, false, true,
                 false, false, false]
  odom0_differential: false
  imu0: /imu/data
  imu0_config: [false, false, false,
                false, false, false,
                false, false, false,
                false, false, true,
                false, false, false]
  imu0_differential: false
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom
